version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      MONGODB_URL: "mongodb+srv://admin:admin@demo.d6mozcq.mongodb.net/?retryWrites=true&w=majority"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
